Add PHP7.4 support and escape symfony YML config
silverstripe/silverstripe-subsites pull request #457
Opened 2020-10-28 09:04 UTC by maxime-rainville

2020-11-05 23:13 UTC, dnsl48 requested changes

2020-11-05 23:13 UTC, dnsl48 commented on _config/middleware.yml
> +        SubsitesStateMiddleware: ''%$SilverStripe\Subsites\Middleware\InitStateMiddleware'
is this a typo?

2020-11-08 19:51 UTC, maxime-rainville commented on _config/middleware.yml
> +        SubsitesStateMiddleware: ''%$SilverStripe\Subsites\Middleware\InitStateMiddleware'
```suggestion
        SubsitesStateMiddleware: '%$SilverStripe\Subsites\Middleware\InitStateMiddleware'
```

2020-11-08 19:52 UTC, maxime-rainville commented on composer.json
> +        "sminnee/phpunit-mock-objects": "^3.4.9",
```suggestion
        "sminnee/phpunit": "^5.7.29"
```

2020-11-08 19:53 UTC, maxime-rainville commented on composer.json
> +        "sminnee/phpunit": "^5.7.29"
```suggestion
        "sminnee/phpunit": "^5.7.29",
```

2020-11-09 00:20 UTC, dnsl48 commented
got another PR, combined with shared travis config - https://github.com/silverstripe/silverstripe-subsites/pull/457

2020-11-09 00:20 UTC, closed without merging