MNT Fix unit test
silverstripe/silverstripe-subsites pull request #621
Opened 2024-12-16 01:58 UTC by emteknetnz

Issue https://github.com/silverstripe/.github/issues/349

2024-12-16 20:11 UTC, GuySartorelli requested changes
Are we sure this behaviour is correct, and isn't indicative of an unintended regression? When changing a test to match a change in behaviour I'd expect to see some explanation of why the behavioural change is correct.

2024-12-16 20:42 UTC, emteknetnz commented
The unit test is simply calling Hierachry::getTreeTitle() which has recently been updated

```php
    public function getTreeTitle(): string
    {
        $owner = $this->getOwner();
        $title = $owner->MenuTitle ?: $owner->Title;
        $owner->extend('updateTreeTitle', $title);
        return Convert::raw2xml($title ?? '');
    }
```

2024-12-16 20:50 UTC, GuySartorelli commented
Right, I get that, but _should_ `raw2xml` be applied there? It looks like it wasn't in the past or this test wouldn't have failed. Does this cause peoples' legitimate HTML to not render correctly in some context? If so that's an unintended regression.

I believe at the time I tested groups in `TreeDropdownField` _without subsites_ but it appears that `GroupSubsites::updateTreeTitle()` adds some _intentional HTML_ which should either not be added if it doesn't display as expected in context that calls `getTreeTitle()` - or if it would display correctly, it should be permitted instead of being escaped (i.e. `raw2xml` called on the title, not on the updated result)

2024-12-16 22:45 UTC, emteknetnz commented
Updated

2024-12-17 20:17 UTC, GuySartorelli requested changes

2024-12-17 20:17 UTC, ChloeSartorelli commented on src/Extensions/GroupSubsites.php
> +    }
This fixes the specific unit test rather than the underlying regression.

If `updateTreeTitle` should permit HTML content, we should change where `raw2xml()` is called _in the method that calls it (in `Hierarchy`)_ so that other `updateTreeTitle` extension hooks can behave as expected

2024-12-17 22:15 UTC, closed without merging

2024-12-17 22:15 UTC, emteknetnz commented
Closed in favour of https://github.com/silverstripe/silverstripe-framework/pull/11516